version: '3.8'

networks:
  bill-net:
    driver: bridge

services:
  postgres-user:
    container_name: postgres-user
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: bill
      POSTGRES_USER: bill
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-user-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bill -d bill"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - bill-net

  app:
    container_name: bill-app
    image: user:0.0.1-SNAPSHOT
    depends_on:
      - postgres-user
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/bill
      SPRING_DATASOURCE_USERNAME: bill
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - bill-net
    ports:
      - "8080:8080"
