version: '3.8'

services:
  postgres-user:
    container_name: postgres-user
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: bill
      POSTGRES_USER: bill
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"  # Map host port 5431 to container port 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bill -d bill" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres-user-data:
